config/routes.rb
Rails.application.routes.draw do
  root "top#top"
  
  resources :users do
    member do
      get :likes, :following, :followers
    end
    collection do
      get 'refresh_token'
    end
  end

  resources :tracks do
    resource :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
      collection do
        get 'search_artist'
        get 'search_album'
        get 'search_track'
      end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get    'login',  to: 'user_sessions#new'
  post   'login',  to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  resources :relationships,       only: [:create, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get '/auth/spotify/callback', to: 'user_sessions#spotify_callback'
  get '/play', to: 'tracks#play'
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user
  belongs_to :song
  has_many :comments,  dependent: :destroy
  has_many :like, dependent: :destroy
  validate :start_must_be_less_than_end
  validates :original_bpm, presence: true
  validates :duration, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :section, presence: true
  validates :bpm, presence: true
  validates :instrument, presence: true

  enum section: { intro: 0, verse: 1, bridge: 2, chorus: 3, solo: 4, ending:5}
  enum instrument: { guitar: 0, bass: 1, drums: 2, keyboard: 3, sax: 4 }

  def liked_by?(user)
    like.exists?(user_id: user.id)
  end

  private

  def start_must_be_less_than_end
    if start_time.present? && end_time.present? && start_time >= end_time
      errors.add(:start_time, "must be less than end position")
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :check_and_refresh_token, only: [:show]

  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find_by(id: params[:id])
    @comments = @track.comments
    @comment = Comment.new
    @spotify_user = current_user.spotify_user
  end

  def new
    @song = RSpotify::Track.find(params[:track_id])
    @album = RSpotify::Album.find(params[:album_id])
    @track = Track.new
  end
  
  def edit
    @track = Track.find_by(id: params[:id])
  end

  def create
    @album, @song = fetch_spotify_album_and_song
  
    unless @album && @song
      return render :new
    end
  
    ActiveRecord::Base.transaction do
      @new_album = find_or_create_album
      @new_song = find_or_create_song(@new_album)
  
      @track = @new_song.tracks.new(track_params.merge(user: current_user))
      
      if @track.save
        redirect_to user_path(current_user)
      else
        render :new
      end
    end
  rescue ActiveRecord::Rollback
    render :new
  end
  

  def update
    @track = Track.find_by(id: params[:id])
    if @track.update(track_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end

  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @user = @track.user
    if @track.destroy
      flash[:notice] = t('messages.delete_success', model: Track.model_name.human)
      redirect_to user_path(@user)
    else
      flash[:alert] = t('messages.delete_failure', model: Track.model_name.human)
      render 'users/show'
    end
  end
  

  def search_track
    @album = RSpotify::Album.find(params[:album_id])
    @tracks = @album.tracks
  end

  def search_album
    @searchartist = RSpotify::Artist.find(params[:artist_id])
    @albums = @searchartist.albums
  end

  def search_artist
    if params[:search].present?
    @searchartists = RSpotify::Artist.search(params[:search])
    end
  end

  private

  def track_params
    params.require(:track).permit(:start_time, :end_time, :section, :bpm, :instrument, :original_bpm, :duration )
  end

  def fetch_spotify_album_and_song
    album_code = params[:track][:album_code]
    song_code = params[:track][:song_code]
    
    album = RSpotify::Album.find(album_code)
    song = RSpotify::Track.find(song_code)
  
    [album, song]
  end
  
  def find_or_create_album
    Album.find_or_create_by(album_code: params[:track][:album_code]) do |album|
      album.title = @album.name
      album.artist_name = @album.artists.first.name
      album.album_image = @album.images[1]['url']
    end
  end
  
  def find_or_create_song(album)
    album.songs.find_or_create_by(song_code: params[:track][:song_code]) do |song|
      song.song_name = @song.name
      song.bpm = @song.audio_features.tempo
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_comment.html.erb
<div class="w-10/12 rounded-lg flex flex-row m-auto">
  <% unless comment.user.blank? %>
       <div id='comment-box', class="w-1/12 h-1/12" >
         <a href="<%= user_path(comment.user_id) %>"><%= comment.user.avatar.attached? ? (image_tag comment.user.avatar, class:"rounded-full") : (image_tag "blank-profile.png", class:"rounded-full") %></a>
            <div class='text-center'>
              <%= comment.user.name unless comment.user.blank? %>
            </div>
        </div>
        <div class='p-2 rounded-lg w-11/12 m-2 bg-gray-200 relative'>
          <%= comment.content %>
            <% if current_user == comment.user%>
              <div id='comment-editer-container', class='flex flex-row absolute bottom-0 right-16 h-14 w-auto h'>
                  <div class="m-2">
                    <%= button_to track_comment_path(comment.track.id,comment.id)  , method: :delete do%>
                      <i class="fa-solid fa-trash"></i>
                    <%end%>
                  </div>
              
              </div>
          <% end %>
        </div>
       
  <% end %>
</div>

app/views/tracks/_like.html.erb
    <div id='like-container'>
      <% if track.liked_by?(current_user) %>
        
        <div><%= button_to track_likes_path(track.id), method: :delete do%>
          <i class="fa-solid fa-heart" style="color: #ff0a0a;"></i>
          <%= track.like.count%>
          <% end %>
        </div>
      <% else %>
     
        <div>
            <%=  link_to track_likes_path(track.id), data: { "turbo-method": :post }  do%>
              <i class="fa-regular fa-heart"></i>
               <%= track.like.count%>
            <% end %>
        </div>
      <% end %>
    </div>

app/views/tracks/_track-back0903.html..erb
<%= link_to track_path(track.id) do %>
    <div id="track-box-<%= track.id %>" class="flex h-60 w-10/12 bg-sky-400 bg-black m-auto rounded-lg mt-9" data-access-token="<%= current_user.access_token %>" data-track-id="<%= track.song.song_code %>">
      <input type="hidden" id="access-token-input" value="<%= current_user.access_token %>">
      <input type="hidden" id="track-id-input" value="<%= track.id %>">
      <input type="hidden" id="song-code-input" value="<%= track.song.song_code %>">
    <div class='flex-cot'>
      <div class="flex w-auto">

          <div id='tempo-box' class='flex bg-sky-100 flex-col ml-auto'>
            <div class="text-7xl"><%= track.bpm %></div>
            <div class="bg-black h-1 w-full"></div>
            <div class="text-7xl"><%= track.song.bpm %></div>
          </div>
      </div>

      <div id='tag-box' class='flex'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold"><%= track.instrument%></div>
          <div class="ml-9 border-double font-semibold"><%= track.section%></div>
        </div>
        <div class='flex ml-52'>
        
          <div class="ml-9 border-double font-semibold" >編集</div>
        </div>
      </div>
    </div>
    </div>
  </div>
<% end %>
  <div class="ml-9 h-9 w-24 border-double font-semibold flex flex-row">
  <% if track.user_id == current_user.id %>
  <div id='track-editer-container'>
    <div class="m-2">
      <%= button_to "delete", track_path(track.id), method: :delete %>
    </div>
    <div class="m-2">
      <%= link_to 'edit', edit_track_path(track.id) %>
    </div>
  </div>
  <% end %>
    <%= render 'tracks/like', track: track %>
  </div>
<%# <script src="https://sdk.scdn.co/spotify-player.js"></script>
<%= javascript_include_tag 'spotify-play' %>

 <div class="card w-96 bg-base-100 shadow-xl">
    <div class='flex flex-row'>
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <%= image_tag track.user.avatar %>
          </div>
      </label>
       <div class='text-cente ml-2 text-center pt-3'>
        <%= track.user.name %>
       </div>
    </div>
  <figure class="px-10 pt-2 relative group">
   <% if track.song.album.album_image %>
      <div class="relative rounded-xl overflow-hidden">
         <%= image_tag track.song.album.album_image, class:'rounded-xl'%>
         <div class="overlay absolute inset-0 bg-black opacity-0 transition-opacity group-hover:opacity-50"></div>
      </div>
   <% end %>
   <span class="font-bold text-white text-5xl absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100">
    <%= "#{((track.bpm.to_f/track.song.bpm) * 100).round(1)}" + '%' %>
   </span>
</figure>

  <div class="card-body items-center ">
    <div class='flex flex-row'>
      <div id='track-info'>
        <h2 class="card-title"><%= track.song.song_name %></h2>
        <p><%= track.song.album.artist_name %></p>
      </div>
      <div id='tempo-box' class='flex flex-col bg-sky-100 ml-4'>
        <div class="text-2xl"><%= track.bpm %></div>
        <div class="bg-green-400 h-1 w-full"></div>
        <div class="text-2xl"><%= track.song.bpm %></div>
    </div>
   </div>
  </div>

      <div id='tag-box' class='flex flex-row mb-2'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold"><%= track.instrument%></div>
          <div class="ml-9 border-double font-semibold"><%= track.section%></div>
        </div>
      </div>

      <div class='flex flex-row'>
        <div id='like-wrapper'class='ml-10'>
           <%= render 'tracks/like', track: track %>
        </div>

        <div id='editer-wrapper' class='flex flex-row ml-auto mr-10'>
          <div id='edit-wrapper'>
            <%= link_to edit_track_path(track.id) do%>
              <i class="fa-solid fa-pen"></i>
            <%end%>
          </div>
          <div id='delete-wrapper' class='ml-8'>
              <%= button_to track_path(track.id), method: :delete do%>
                <i class="fa-solid fa-trash"></i>
              <%end%>
          </div>
        </div>
      </div>

</div>
   

app/views/tracks/_track.html copy.erb
<%= link_to track_path(track.id) do %>
    <div id="track-box-<%= track.id %>" class="flex h-60 w-10/12 bg-sky-400 bg-black m-auto rounded-lg mt-9" data-access-token="<%= current_user.access_token %>" data-track-id="<%= track.song.song_code %>">
      <input type="hidden" id="access-token-input" value="<%= current_user.access_token %>">
      <input type="hidden" id="track-id-input" value="<%= track.id %>">
      <input type="hidden" id="song-code-input" value="<%= track.song.song_code %>">
    <div class='flex-cot'>
      <div class="flex w-auto">
        <div class="flex flex-col ml-9 mr-90">
          <div id='artist-box' class='mt-9 font-semibold'><%= track.song.album.artist_name %></div>
          <div id='title-box' class='mt-9 font-semibold'><%= track.song.song_name %></div>
        </div>
        <div id='album-image-box' class='rounded'> 
          <% if track.song.album.album_image %>
            <%= image_tag track.song.album.album_image, class:'rounded'%>
          <% end %>

        </div>

          <div id='tempo-box' class='flex bg-sky-100 flex-col ml-auto'>
            <div class="text-7xl"><%= track.bpm %></div>
            <div class="bg-black h-1 w-full"></div>
            <div class="text-7xl"><%= track.song.bpm %></div>
          </div>
      </div>

      <div id='tag-box' class='flex'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold"><%= track.instrument%></div>
          <div class="ml-9 border-double font-semibold"><%= track.section%></div>
        </div>
        <div class='flex ml-52'>
        
          <div class="ml-9 border-double font-semibold" >編集</div>
        </div>
      </div>
    </div>
    </div>
  </div>
<% end %>
  <div class="ml-9 h-9 w-24 border-double font-semibold flex flex-row">
  <% if track.user_id == current_user.id %>
  <div id='track-editer-container'>
    <div class="m-2">
      <%= button_to "delete", track_path(track.id), method: :delete %>
    </div>
    <div class="m-2">
      <%= link_to 'edit', edit_track_path(track.id) %>
    </div>
  </div>
  <% end %>
    <div id='like-container'>
      <% if track.liked_by?(current_user) %>
        <%= track.like.count%>
        <div><%= button_to track_likes_path(track.id), method: :delete do%>
          <i class="fa-solid fa-heart" style="color: #ff0a0a;"></i>
          <% end %>
        </div>
      <% else %>
      <%= track.like.count%>
        <div>
            <%=  link_to track_likes_path(track.id), data: { "turbo-method": :post }  do%>
              <i class="fa-regular fa-heart"></i>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
<%# <script src="https://sdk.scdn.co/spotify-player.js"></script>
<%= javascript_include_tag 'spotify-play' %>

 
   

app/views/tracks/_track.html.erb
<div id='track-card' class="card w-96 bg-gray-700 shadow-xl m-5">
      <input type="hidden" id="access-token-input" value="<%= current_user.access_token %>">
      <input type="hidden" id="track-id-input" value="<%= track.id %>">
      <input type="hidden" id="song-code-input" value="<%= track.song.song_code %>">
    <div class='flex flex-row mt-3 ml-2'>
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
              <%= track.user.avatar.attached? ? (image_tag track.user.avatar, class:"rounded-full") : (image_tag "blank-profile.png", class:"rounded-full") %>
          </div>
      </label>
      <div class='text-cente ml-2 text-center pt-3'>
        <%= track.user.name %>
      </div>
    </div>
  <%= link_to track_path(track.id) do %>
    <figure class="px-10 pt-2 relative group">
      <% if track.song.album.album_image %>
          <div class="relative rounded-xl overflow-hidden">
            <%= image_tag track.song.album.album_image, class:'rounded-xl'%>
            <div class="overlay absolute inset-0 bg-black opacity-0 transition-opacity group-hover:opacity-50"></div>
          </div>
      <% end %>
      <span class="font-bold text-white text-5xl absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100">
        <%= "#{((track.bpm.to_f/track.song.bpm) * 100).round(1)}" + '%' %>
      </span>
    </figure>
  <% end %>

  <div class="card-body items-center ">
    <div class='flex flex-row'>
      <div id='track-info'>
        <h2 class="card-title"><%= track.song.song_name %></h2>
        <p><%= track.song.album.artist_name %></p>
      </div>
      <div id='tempo-box' class='flex flex-col bg-sky-100 ml-4'>
        <div class="text-2xl"><%= track.bpm %></div>
        <div class="bg-green-400 h-1 w-full"></div>
        <div class="text-2xl"><%= track.song.bpm %></div>
    </div>
   </div>
  </div>

      <div id='tag-box' class='flex flex-row mb-2'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold"><%= track.instrument%></div>
          <div class="ml-9 border-double font-semibold"><%= track.section%></div>
        </div>
      </div>

      <div class='flex flex-row'>
        <div id='like-wrapper'class='ml-10'>
          <%= render 'tracks/like', track: track %>
        </div>
        <% if current_user.own?(track)%>
        <div id='editer-wrapper' class='flex flex-row ml-auto mr-10 mb-3'>
          <div id='edit-wrapper'>
            <%= link_to edit_track_path(track.id) do%>
              <i class="fa-solid fa-pen"></i>
            <%end%>
          </div>
          <div id='delete-wrapper' class='ml-8'>
              <%= button_to track_path(track.id), method: :delete do%>
                <i class="fa-solid fa-trash"></i>
              <%end%>
          </div>
        </div>
        <% end %>
      </div>
</div>

app/views/tracks/_track.html_copy.erb
<%= link_to track_path(track.id) do %>
    <div id="track-box-<%= track.id %>" class="flex h-60 w-10/12 bg-sky-400 bg-black m-auto rounded-lg mt-9" data-access-token="<%= current_user.access_token %>" data-track-id="<%= track.song.song_code %>">
      <input type="hidden" id="access-token-input" value="<%= current_user.access_token %>">
      <input type="hidden" id="track-id-input" value="<%= track.id %>">
      <input type="hidden" id="song-code-input" value="<%= track.song.song_code %>">
    <div class='flex-cot'>
      <div class="flex w-auto">
        <div class="flex flex-col ml-9 mr-90">
          <div id='artist-box' class='mt-9 font-semibold'><%= track.song.album.artist_name %></div>
          <div id='title-box' class='mt-9 font-semibold'><%= track.song.song_name %></div>
        </div>
        <div id='album-image-box' class='rounded'> 
          <% if track.song.album.album_image %>
            <%= image_tag track.song.album.album_image, class:'rounded'%>
          <% end %>

        </div>

          <div id='tempo-box' class='flex bg-sky-100 flex-col ml-auto'>
            <div class="text-7xl"><%= track.bpm %></div>
            <div class="bg-black h-1 w-full"></div>
            <div class="text-7xl"><%= track.song.bpm %></div>
          </div>
      </div>

      <div id='tag-box' class='flex'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold"><%= track.instrument%></div>
          <div class="ml-9 border-double font-semibold"><%= track.section%></div>
        </div>
        <div class='flex ml-52'>
        
          <div class="ml-9 border-double font-semibold" >編集</div>
        </div>
      </div>
    </div>
    </div>
  </div>
<% end %>
  <div class="ml-9 h-9 w-24 border-double font-semibold flex flex-row">
  <% if track.user_id == current_user.id %>
  <div id='track-editer-container'>
    <div class="m-2">
      <%= button_to "delete", track_path(track.id), method: :delete %>
    </div>
    <div class="m-2">
      <%= link_to 'edit', edit_track_path(track.id) %>
    </div>
  </div>
  <% end %>
    <div id='like-container'>
      <% if track.liked_by?(current_user) %>
        <%= track.like.count%>
        <div><%= button_to track_likes_path(track.id), method: :delete do%>
          <i class="fa-solid fa-heart" style="color: #ff0a0a;"></i>
          <% end %>
        </div>
      <% else %>
      <%= track.like.count%>
        <div>
            <%=  link_to track_likes_path(track.id), data: { "turbo-method": :post }  do%>
              <i class="fa-regular fa-heart"></i>
            <% end %>
        </div>
      <% end %>
    </div>
  </div>
<%# <script src="https://sdk.scdn.co/spotify-player.js"></script>
<%= javascript_include_tag 'spotify-play' %>

 
   

app/views/tracks/create.html.erb
<header>
ヘッダーです
</header>

app/views/tracks/index.html.erb
<h1><%= t(".title")%></h1>
<div class="flex flex-col items-center bg-green-400 p-10">
    <%= render @tracks %>
</div>
<div class="flex items-center justify-center h-20">
  <%= link_to t(".back"), :back, class: "text-lg text-blue-500 hover:text-blue-700 hover:underline hover:bg-blue-100 p-2 rounded transition duration-300 ease-in-out" %>
</div>

app/views/tracks/play.html.erb
<!-- app/views/songs/play.html.erb -->

<!DOCTYPE html>
<html>
<head>
  <title>Spotify Web Playback SDK Quick Start</title>
</head>
<body>
  <h1>Spotify Web Playback SDK Quick Start</h1>
  <button id="togglePlay">Toggle Play</button>
  <%= include_gon %>
  <script src="https://sdk.scdn.co/spotify-player.js"></script>
   <%# <%= javascript_include_tag 'play.js' %> %>
</body>
</html>

app/views/tracks/search_album.html.erb
<h1><%= t(".title") %></h1>
<div>
  <% if @albums.present? %>
    <% @albums.each do |album| %>
      <div>

        <h3><%= album.name %></h3>
          <% if album.images.any?%>
            <%image = album.images[1]%>
            <%= link_to   search_track_tracks_path(album_id: album.id) do %>
              <%= image_tag(image["url"])%>
            <%end%>
          <%else%>
            <%= image_tag("noimage.png")%>
          <%end%>
      </div>
    <%end%>
  <%end%>
</div>

app/views/tracks/search_artist.html.erb
<h1><%= t(".title") %></h1>

<%= form_with url: search_artist_tracks_path, method: :get, local: true do |form| %>
<%= form.text_field :search %>
<%= form.submit t(".search"), name: nil %>
<% end %>


<h1><%=t(".result")%></h1>
<div>
  <% if @searchartists.present? %>
    <% @searchartists.each do |searchartist| %>
      <div>
        <%= link_to searchartist.name,search_album_tracks_path(artist_id: searchartist.id) %>
        <h3><%= searchartist.name %></h3>
          <% if searchartist.images.any?%>
            <%image = searchartist.images[1]%>
            <%= image_tag(image["url"])%>
          <%else%>
            <%= image_tag("noimage.png")%>
          <%end%>
      </div>
    <%end%>
  <%end%>
</div>

app/views/tracks/search_track.html.erb
<h1><%= t(".title")%></h1>
<div>
  <% if @tracks.present? %>
     <%image = @album.images[1]%>
     <%= image_tag(image["url"])%>

    <% @tracks.each do |track| %>
      <div class='w-auto h-4 bg-gray-300'>
        <h3><%= link_to track.name, new_track_path(album_id: @album.id ,track_id: track.id)  %></h3>
      </div>
    <%end%>
  <%end%>
</div>

app/views/tracks/show.html.erb
<div id="edit-container">
  <div class="flex flex-col items-center bg-green-400 p-10">
    <%= render @track %>
    <button id="start-loop-button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5"><i class="fa-solid fa-play"></i></button>
  </div>
    <input type="hidden" id="access-token-input" value="<%= current_user.access_token%>">
    <input type="hidden" id="track-id-input" value="<%= @track.id %>">
    <input type="hidden" id="song-code-input" value="<%= @track.song.song_code %>">
    <input type="hidden" id="start-time-input" value="<%= @track.start_time %>">
    <input type="hidden" id="end-time-input" value="<%= @track.end_time %>">
  </div>
  <div class="comment-wrapper border-top mb-10">
    <p class="text-center mt-2 font-bold"><%= t(".comment")%></p>
    <% if @comments %>
      <%= render partial:'comment', collection: @comments%>
    <% end %>
  </div>
  <div id='comment-textbox-wrapper' class='border-solid border-2 border-gray-500 flex flex-col items-center justify-center' style='height: 50vh;'>
    <%= form_with(model: @comment, url: track_comments_path(@track), local: true) do |f| %>
      <div class='w-11/12'>
        <%= f.text_area :content, class: "border-solid border-2 border-gray-400", cols:"60", rows: 5 %>
      </div>
      <%= f.submit t(".submit"), class: "btn btn-success mt-1" %>
    <% end %>
  </div>
  <div class="flex items-center justify-center h-20">
    <%= link_to t(".back"), :back, class: "text-lg text-blue-500 hover:text-blue-700 hover:underline hover:bg-blue-100 p-2 rounded transition duration-300 ease-in-out" %>
  </div>

  <script src="https://sdk.scdn.co/spotify-player.js"></script>
  <%= javascript_include_tag 'spotify-play' %>

  <% content_for :head do %>
    <meta name="turbo-visit-control" content="reload">
  <% end %>
</div>