config/routes.rb
Rails.application.routes.draw do
  root "top#top"
  
  resources :users do
    member do
      get :likes, :following, :followers
    end
    collection do
      get 'refresh_token'
    end
  end

  resources :tracks do
    resource :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
      collection do
        get 'search_artist'
        get 'search_album'
        get 'search_track'
      end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get    'login',  to: 'user_sessions#new'
  post   'login',  to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  resources :relationships,       only: [:create, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get '/auth/spotify/callback', to: 'user_sessions#spotify_callback'
  get '/play', to: 'tracks#play'
end

app/models/user.rb
class User < ApplicationRecord

  authenticates_with_sorcery!

  has_one_attached :avatar
  has_many :tracks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy,
                                  inverse_of: :follower
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy,
                                  inverse_of: :followed
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, uniqueness: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password, presence: true, confirmation: true, length: {minimum: 6}, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :access_token, presence: true
  validates :refresh_access_token, presence: true


  enum role: { general: 0, admin: 1 }
  enum instrument: { guitar: 0, bass: 1, drums: 2, keyboard: 3, sax: 4 }

  def self.find_or_create_from_omniauth!(auth_hash)
    user = User.find_or_initialize_by(user_code: auth_hash[:uid])
    random_password = SecureRandom.hex(16)

    user.update!(
      email: auth_hash[:info][:email],
      name: auth_hash[:info][:display_name],
      avatar: auth_hash[:info][:image],
      user_code: auth_hash[:uid],
      password: random_password,
      password_confirmation: random_password,
      access_token: auth_hash[:credentials][:token],
      refresh_access_token: auth_hash[:credentials][:refresh_token],
      token_deadline: auth_hash[:credentials][:expires_at],
      instrument: 0
    )
    user
  end

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def own?(object)
    object.user_id == id
  end

  def spotify_user
    callback_proc = Proc.new do |new_access_token, token_lifetime|
      now = Time.now.utc.to_i
      deadline = now+token_lifetime
      self.update!(access_token: new_access_token, token_deadline: deadline)
    end

    user_credentials = {
      'token' => self.access_token,
      'refresh_token' => self.refresh_access_token,
      'access_refresh_callback' => callback_proc
    }

    RSpotify::User.new(
      {
        'credentials' => user_credentials,
        'id' => self.user_code
      }
    )
  end

  def refresh_spotify_token!
    user = spotify_user
    # RSpotifyがトークンの有効性を確認し、必要に応じてリフレッシュを行います。
    user.playlists # この操作により、トークンが有効か確認され、リフレッシュが行われる可能性があります。
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[create new] 
  before_action :set_user, only: [:edit, :update, :likes, :following, :followers]
  
  def index; end

  def show
    @user = User.includes(tracks: {song: :album}).find_by(id: params[:id])
    @tracks = @user.tracks
  end

  def new
    @user = User.new
    @spotify_user_info = session[:spotify_user_info]
    @email = @spotify_user_info['email']
    @name = @spotify_user_info['name']
    @image_url = @spotify_user_info['images'][0]['url']
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
      flash[:notice] = t('messages.success', model: User.model_name.human)
    else
      flash.now[:alert] = t('messages.failure', model: User.model_name.human)
      render :new
    end
  end

  def update
    if @user.update(user_edit_params)
      @user.avatar.attach(params[:user][:avatar]) if params[:user][:avatar]
      redirect_to @user, notice: t('messages.update_success', model: User.model_name.human)
    else
      flash.now[:alert] = t('messages.update_failure', model: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy; end

  def spotify
    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    session[:access_token] = @spotify_user.credentials.token
    session[:refresh_token] = @spotify_user.credentials.refresh_token
  end
  
  def likes
    likes = Like.where(user_id: @user.id).pluck(:track_id)
    @like_tracks = Track.find(likes)
  end

  def following
    @title = User.human_attribute_name(:following)
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @title = User.human_attribute_name(:followed)
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :instrument, :avatar).merge(
      access_token: session[:access_token],
      refresh_access_token: session[:refresh_token],
      token_deadline: session[:token_deadline],
      user_code: session[:spotify_user_info]['id'] 
    )
  end

  def user_edit_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :instrument, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "text-white py-2 px-4 rounded bg-green-500 hover:bg-green-300" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <%= render 'shared/error_messages' %>
  
  
  
  <%= f.label :email %>
  <%= f.text_field :email, value:@spotify_user_info['email'] %>
  <%= f.label :name %>
  <%= f.text_field :name, value:@spotify_user_info['name'] %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.select :instrument, User.instruments.keys %>
  
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, id: 'user_avatar', value: @spotify_user_info['images'][0]['url'] %>
  </div>
  <div id="avatar-preview-container"></div>
  
  <%= f.submit "保存" %>
<% end %>

<style>
  .avatar-preview {
    max-width: 200px;
    max-height: 200px;
    border-radius: 50%;
  }
</style>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        var previewContainer = document.getElementById('avatar-preview-container');
        previewContainer.innerHTML = '<img src="' + e.target.result + '" alt="Avatar Preview" class="avatar-preview">';
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  document.getElementById('user_avatar').addEventListener('change', function() {
    readURL(this);
  });
</script>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed: @user),
              html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "text-white py-2 px-4 rounded bg-gray-400 hover:bg-gray-300" %>
<% end %>

app/views/users/_user.html.erb
<div class='flex flex-row bg-green-200 w-2/5 rounded'>
<%= link_to user_path(user) do%>
<%= user.avatar.attached? ? (image_tag user.avatar, class:"rounded-full h-32 w-32 m-2") : (image_tag "blank-profile.png", class:"rounded-full") %>
<%end%>
  <div class='flex flex-col'>
    <%= link_to user_path(user) do%>
    <p class='font-bold ml-10 mt-2'><%= user.name%></p>
    <% end %>
    <p class='font-bold ml-10 mt-2 border-double border-4 border-sky-500 text-center rounded-md'><%= user.instrument%></p>
</div>

app/views/users/edit.html.erb
<h1><%= t(".title") %></h1>
<%= form_with model: @user do |f| %>
  <%= render 'shared/error_messages' %>
  
  
  
  <%= f.label :email %>
  <%= f.text_field :email, value:@user.email %>
  <%= f.label :name %>
  <%= f.text_field :name, value:@user.name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.select :instrument, User.instruments.keys.map { |key| [I18n.t("activerecord.enums..user.instrument.#{key}"), key] } %>
  
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, id: 'user_avatar', value: @user.avatar %>
  </div>
  <div id="avatar-preview-container"></div>
  
  <%= f.submit t(".update") %>
<% end %>

<div class="flex items-center justify-center h-20">
  <%= link_to t(".back"), :back, class: "text-lg text-blue-500 hover:text-blue-700 hover:underline hover:bg-blue-100 p-2 rounded transition duration-300 ease-in-out" %>
</div>

<style>
  .avatar-preview {
    max-width: 200px;
    max-height: 200px;
    border-radius: 50%;
  }
</style>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        var previewContainer = document.getElementById('avatar-preview-container');
        previewContainer.innerHTML = '<img src="' + e.target.result + '" alt="Avatar Preview" class="avatar-preview">';
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  document.getElementById('user_avatar').addEventListener('change', function() {
    readURL(this);
  });
</script>

app/views/users/likes.html.erb
<h1><%= t(".title")%></h1>
<div id="track-container" class='grid grid-cols-3 gap-4'>
  <% if @like_tracks.any? %>
        <%= render  @like_tracks %>
  <% else %>
    <p><%= t(".message")%></p>
  <% end %>
</div>
<div class="flex items-center justify-center h-20">
  <%= link_to t(".back"), :back, class: "text-lg text-blue-500 hover:text-blue-700 hover:underline hover:bg-blue-100 p-2 rounded transition duration-300 ease-in-out" %>
</div>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <%= render 'shared/error_messages' %>
  

  <%= f.label :email %>
  <%= f.text_field :email, value:@email %>
  <%= f.label :name %>
  <%= f.text_field :name, value:@name %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.select :instrument, User.instruments.keys %>
  
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, id: 'user_avatar', value: @image_url %>
  </div>
  <div id="avatar-preview-container"></div>
  
  <%= f.submit "保存" %>
<% end %>

<style>
  .avatar-preview {
    max-width: 200px;
    max-height: 200px;
    border-radius: 50%;
  }
</style>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        var previewContainer = document.getElementById('avatar-preview-container');
        previewContainer.innerHTML = '<img src="' + e.target.result + '" alt="Avatar Preview" class="avatar-preview">';
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  document.getElementById('user_avatar').addEventListener('change', function() {
    readURL(this);
  });
</script>

app/views/users/show.html.erb
<body>

  <!-- Hero section with heading, subheading and button -->
  <div id='user-image-container'
    class="bg-neutral-50 px-6 py-20 text-center text-neutral-800 dark:bg-neutral-700 dark:text-neutral-200 ">
    <div class="w-1/12 h-1/12 m-auto" ><%= @user.avatar.attached? ? (image_tag @user.avatar, class:"rounded-full") : (image_tag "blank-profile.png", class:"rounded-full") %></div>
    <h3 class="mb-8 text-3xl font-bold mt-10"><%= @user.name%></h3>
    <div id='follow-btn-wrapper', class='w-auto h-auto'>
      <%= render 'follow_form' if logged_in? %>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
  </div>
  </div>
  
</header>
<div id='serecter', class='flex flex-row w-auto'>
  <div class='bg-gray-300 w-1/2 h-16 border-2 border-gray-100 rounded text-center py-2 hover:opacity-75 flex items-center justify-center cursor-pointer'>
    <div>
      <p class='font-medium leading-relaxed'><%= t(".track")%></p>
    </div>
  </div>
  <div class='bg-gray-300 w-1/2 h-16 border-2 border-gray-100 rounded text-center py-2 hover:opacity-75 flex items-center justify-center cursor-pointer'>
    
    <%= link_to t(".like"),likes_user_path(@user), class:'font-medium'%>
  </div>
</div>
  <div id="track-container" class='grid grid-cols-3 gap-4'>
  
    <%=  render  @tracks %>

  </div>
  <div class="fixed right-20 bottom-20 cursor-pointer z-50">
    <%= link_to image_tag('create-96.png'),  search_artist_tracks_path %>
  </div>
</body>

app/views/users/show_follow.html copy.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><strong>Tracks:</strong> <%= @user.tracks.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to user do %>
              <%= user.avatar.attached? ? (image_tag user.avatar, class:"rounded-full") : (image_tag "blank-profile.png", class:"rounded-full") %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= paginate @users %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><strong>Tracks:</strong> <%= @user.tracks.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>

    </section>
  </aside>
  <div class="col-md-8">
    <p class='font-bold text-2xl'><%= @title %></p>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= paginate @users %>
    <% end %>
  </div>
</div>
<div class="flex items-center justify-center h-20">
  <%= link_to t(".back"), :back, class: "text-lg text-blue-500 hover:text-blue-700 hover:underline hover:bg-blue-100 p-2 rounded transition duration-300 ease-in-out" %>
</div>

app/views/users/spotify.html.erb
<p>spotify</p>