config/routes.rb
Rails.application.routes.draw do
  root "top#top"
  
  resources :users do
    member do
      get :likes, :following, :followers
    end
    collection do
      get 'refresh_token'
    end
  end

  resources :tracks do
    resource :likes, only: [:index, :create, :destroy]
    resources :comments, only: [:create, :destroy]
      collection do
        get 'search_artist'
        get 'search_album'
        get 'search_track'
      end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get    'login',  to: 'user_sessions#new'
  post   'login',  to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  resources :relationships,       only: [:create, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"
  get '/auth/spotify/callback', to: 'user_sessions#spotify_callback'
  get '/play', to: 'tracks#play'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-blue-700 bg-blue-100 rounded-lg dark:bg-blue-200 dark:text-blue-800" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="p-4 mt-3 mb-4 mx-3 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-4 bg-base-300 text-base-content sticky bottom-0">
  <div>
    <p>Copyright © 2023 - All right reserved by okjm</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div>
    <nav class="bg-white dark:bg-gray-800  shadow ">
        <div class="px-8 mx-auto max-w-7xl">
            <div class="flex items-center justify-between h-16">
                <div class=" flex items-center">
                    <a class="flex-shrink-0" href="/">
                        <img class="w-8 h-8" src="/icons/rocket.svg" alt="Workflow"/>
                    </a>
                    <div class="hidden md:block">
                        <div class="flex items-baseline ml-10 space-x-4">
                            <a class="text-gray-300  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/#">
                                Home
                            </a>
                            <a class="text-gray-800 dark:text-white  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/#">
                                Gallery
                            </a>
                            <a class="text-gray-300  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/#">
                                Content
                            </a>
                            <a class="text-gray-300  hover:text-gray-800 dark:hover:text-white px-3 py-2 rounded-md text-sm font-medium" href="/#">
                                Contact
                            </a>
                        </div>
                    </div>
                </div>
                <div class="block">
                    <div class="flex items-center ml-4 md:ml-6">
                        <div class="relative ml-3">
                            <div class="relative inline-block text-left">
                                <div>
                                    <button type="button" class="  flex items-center justify-center w-full rounded-md  px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-50 hover:bg-gray-50 dark:hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-gray-500" id="options-menu">
                                        <svg width="20" fill="currentColor" height="20" class="text-gray-800" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M1523 1339q-22-155-87.5-257.5t-184.5-118.5q-67 74-159.5 115.5t-195.5 41.5-195.5-41.5-159.5-115.5q-119 16-184.5 118.5t-87.5 257.5q106 150 271 237.5t356 87.5 356-87.5 271-237.5zm-243-699q0-159-112.5-271.5t-271.5-112.5-271.5 112.5-112.5 271.5 112.5 271.5 271.5 112.5 271.5-112.5 112.5-271.5zm512 256q0 182-71 347.5t-190.5 286-285.5 191.5-349 71q-182 0-348-71t-286-191-191-286-71-348 71-348 191-286 286-191 348-71 348 71 286 191 191 286 71 348z">
                                            </path>
                                        </svg>
                                    </button>
                                </div>
                                <div class="absolute right-0 w-56 mt-2 origin-top-right bg-white rounded-md shadow-lg dark:bg-gray-800 ring-1 ring-black ring-opacity-5">
                                    <div class="py-1 " role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                                        <a href="#" class="block block px-4 py-2 text-md text-gray-700 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-100 dark:hover:text-white dark:hover:bg-gray-600" role="menuitem">
                                            <span class="flex flex-col">
                                                <span>
                                                    Settings
                                                </span>
                                            </span>
                                        </a>
                                        <a href="#" class="block block px-4 py-2 text-md text-gray-700 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-100 dark:hover:text-white dark:hover:bg-gray-600" role="menuitem">
                                            <span class="flex flex-col">
                                                <span>
                                                    Account
                                                </span>
                                            </span>
                                        </a>
                                        <a href="#" class="block block px-4 py-2 text-md text-gray-700 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-100 dark:hover:text-white dark:hover:bg-gray-600" role="menuitem">
                                            <span class="flex flex-col">
                                                <span>
                                                    Logout
                                                </span>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="flex -mr-2 md:hidden">
                    <button class="text-gray-800 dark:text-white hover:text-gray-300 inline-flex items-center justify-center p-2 rounded-md focus:outline-none">
                        <svg width="20" height="20" fill="currentColor" class="w-8 h-8" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path d="M1664 1344v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45zm0-512v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45zm0-512v128q0 26-19 45t-45 19h-1408q-26 0-45-19t-19-45v-128q0-26 19-45t45-19h1408q26 0 45 19t19 45z">
                            </path>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
        <div class="md:hidden">
            <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <a class="text-gray-300 hover:text-gray-800 dark:hover:text-white block px-3 py-2 rounded-md text-base font-medium" href="/#">
                    Home
                </a>
                <a class="text-gray-800 dark:text-white block px-3 py-2 rounded-md text-base font-medium" href="/#">
                    Gallery
                </a>
                <a class="text-gray-300 hover:text-gray-800 dark:hover:text-white block px-3 py-2 rounded-md text-base font-medium" href="/#">
                    Content
                </a>
                <a class="text-gray-300 hover:text-gray-800 dark:hover:text-white block px-3 py-2 rounded-md text-base font-medium" href="/#">
                    Contact
                </a>
            </div>
        </div>
    </nav>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <% if logged_in? %>
      <%= link_to t(".appname"), user_path(current_user), class:"btn btn-ghost normal-case text-xl" %>
    <% else %>
      <%= link_to t(".appname"), root_path, class:"btn btn-ghost normal-case text-xl" %>
    <% end %>
  </div>
  <% if logged_in? %>
  <div class="flex-none gap-2">
    <div class="dropdown dropdown-end">
      <label tabindex="0" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <%= current_user.avatar.attached? ? (image_tag current_user.avatar, class:"rounded-full") : (image_tag "blank-profile.png", class:"rounded-full") %>
        </div>
      </label>
      <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
        <li><%= link_to t(".mypage"), user_path(current_user), id: 'mypage-link'%></li>
        <li><%= link_to t(".timeline"), tracks_path, id: 'timeline-link'%></li>
        <li><%= link_to t(".setting"), edit_user_path(current_user), id: 'setting-link'%></li>
        <li><%= link_to t(".logout"), :logout, id: 'sign-out-link', data: { "turbo-method": :delete } %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
     <%= I18n.t('shared.stats.following') %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= I18n.t('shared.stats.followed') %>
  </a>
</div>

app/views/shared/_track.html.erb
    <div id='track-box' class="flex h-60 w-10/12 bg-sky-400 bg-black m-auto rounded-lg mt-9" >
    <div class='flex-cot'>
      <div class="flex w-auto">
        <div class="flex flex-col ml-9 mr-90">
          <div id='artist-box' class='mt-9 font-semibold'>アーティスト</div>
          <div id='title-box' class='mt-9 font-semibold'>タイトル</div>
        </div>

          <div id='tempo-box' class='flex bg-sky-100 flex-col ml-auto'>
            <div class="text-7xl">200</div>
            <div class="bg-black h-1 w-full"></div>
            <div class="text-7xl">200</div>
          </div>

      </div>

      <div id='tag-box' class='flex'>
        <div class='flex'>
          <div class="ml-9 border-double font-semibold">gu</div>
          <div class="ml-9 border-double font-semibold">サビ</div>
        </div>
        <div class='flex ml-52'>
          <div class="ml-9 h-9 w-24 border-double font-semibold">削除</div>
          <div class="ml-9 border-double font-semibold" >編集</div>
        </div>
      </div>
    </div>
    </div>

  </div>
<script>
  document.addEventListener('DOMContentLoaded', function() {

  const track_box =  document.getElementById("track-box")

  track_box.addEventListener('click', ()=>{
    console.log('clicked')

  })
});
</script>
 
   